---
- name: "Create Initial Rings: Account ring"
  hosts: controller
  roles:
    - config
  become: True
  gather_facts: True

  tasks:

  - name: "Create the base account.builder file: with 2^10 (1024) maximum partitions, 3 replicas of each object, and 1 hour minimum time between moving a partition"
    shell: "cd /etc/swift; swift-ring-builder account.builder create 10 3 1"

  - name: "Add each storage node to the ring DEVICE 1"
    shell: "cd /etc/swift; swift-ring-builder account.builder add r1z1-{{ item }}:6002/{{ config.object_partition_1_name }} 100"
    with_items: "{{ groups['object'] }}"

  - name: "Add each storage node to the ring DEVICE 2"
    shell: "cd /etc/swift; swift-ring-builder account.builder add r1z2-{{ item }}:6002/{{ config.object_partition_2_name }} 100"
    with_items: "{{ groups['object'] }}"

  - name: "Verify the ring contents:"
    shell: "cd /etc/swift; swift-ring-builder account.builder"

  - name: "Rebalance the ring:"
    shell: "cd /etc/swift; swift-ring-builder account.builder rebalance"