---
# https://www.unix-ag.uni-kl.de/~bloch/acng/html/config-servquick.html#server-config
- name: install & start the apt-cacher-ng service
  hosts: aptcache
  roles:
    - config
  become: True

  tasks:

  - name: "install apt-cacher-ng"
    apt: pkg=apt-cacher-ng state=installed update_cache=yes

#  - name: "set proxy"
#    lineinfile: dest=/etc/apt-cacher-ng/acng.conf
#                  line='offlinemode:1'
#                  state=present
#                  create=yes

