---
# http://docs.openstack.org/kilo/install-guide/install/apt/content/neutron_initial-networks-verify.html
- name:  "Add a networking component > Create initial networks > Verify network connectivity"
  hosts: localhost
  become: false
  roles:
    - config
  gather_facts: False
  tasks:

  - name: From a host on the the external network, ping the tenant router gateway
    shell: ping -c 20 "{{ config.tenant_router_gateway_external_ip_address }}"

