---
# http://docs.openstack.org/kilo/install-guide/install/apt/content/ch_nova.html
- name:  "Add the Compute service > Install and configure controller node > finalize installation"
  hosts: controller
  roles:
    - config
  become: True
  gather_facts: False
  tasks:

  - name: "1. Restart the Compute services"
    service: 
      name: "{{ item }}"
      state: restarted
    with_items:
    - nova-api
    - nova-api-metadata
    - nova-cert
    - nova-consoleauth
    - nova-scheduler
    - nova-conductor
    - nova-novncproxy

  - name: "2. Because this configuration uses a SQL database server, you can remove the SQLite database file"
    # By default, the Ubuntu packages create an SQLite database
    shell: "rm -f /var/lib/nova/nova.sqlite"
