---
# http://docs.openstack.org/kilo/install-guide/install/apt/content/neutron-compute-node.html
- name:  "Add a networking component > Install and configure compute node > configure prerequisites"
  hosts: compute
  roles:
    - config
  become: True
  gather_facts: False
  tasks:
    - name: "1. Edit the /etc/sysctl.conf file to contain the following parameters"
      lineinfile: 
        dest: /etc/sysctl.conf
        line: "{{ item }}"
        state: present
        create: yes
      with_items:
      - "net.ipv4.conf.all.rp_filter=0"
      - "net.ipv4.conf.default.rp_filter=0"
      - "net.bridge.bridge-nf-call-iptables=1"
      - "net.bridge.bridge-nf-call-ip6tables=1"

    - name: "2. Implement the changes"
      shell: "sysctl -p"
