---
# http://docs.openstack.org/kilo/install-guide/install/apt/content/neutron-compute-node.html
- name:  "Add a networking component > Install and configure compute node > install the Networking components"
  hosts: compute
  become: True
  gather_facts: False
  tasks:

    - name: "1. Install the packages"
      apt: pkg={{item}} state=installed
      with_items:
      - neutron-plugin-ml2
      - neutron-plugin-openvswitch-agent


