---
# http://docs.openstack.org/kilo/install-guide/install/apt/content/neutron-compute-node.html
- name:  "Add a networking component > Install and configure compute node > configure the Open vSwitch (OVS) service"
  hosts: compute
  roles:
    - config
  become: True
  gather_facts: False
  tasks:

    - name: "1. Restart the OVS service"
      shell: "service openvswitch-switch restart"


