#!/bin/sh


# see https://raw.githubusercontent.com/kumina/shutdown-kvm-guests/master/shutdown-kvm-guests.sh

echo "Shutting all VMs down"

for virtual_machine_name in `tools/vm_names`
do
        (virsh shutdown $virtual_machine_name || exit 2) &
done

wait
